# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c66d587b4effc1089516a8cd623e2a8c749d3aef74bcf3dabdb11ca684dfcd50a0c9d01744fffd87783346a27f81bccc52e3c27910cb6469b53d743b8e85901c

test:
  secret_key_base: 4900355c88e6bc67c304484268ae5148e0652ae3252d95d287dd0339d9e6e6178773661698d89e06fc4ab8897267196e13ad4b7bb81646da6fa52033b4ba3c54

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
